server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jakarta.persistence.jdbc.url: ${DB_URL}
      jakarta.persistence.jdbc.user: ${DB_USER}
      jakarta.persistence.jdbc.password: ${DB_PASSWORD}